version: '3'
services:
  db:
    build: ./mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: pass
  php:
    build: ./php
    volumes:
      - ./src:/src
    depends_on:
      - db
